language: ruby

rvm:
  - 2.1.8
  - 2.2.4
  - 2.3.0

gemfile:
  - gemfiles/Gemfile.rails32
  - gemfiles/Gemfile.rails41
  - gemfiles/Gemfile.rails42

sudo: false

cache: bundler

bundler_args: --without development

before_install: "rm ${BUNDLE_GEMFILE}.lock"

before_script: "bundle update"

script: "bundle exec rake test"
